export const ACTIONS = {
  GET_CONTACTS: 'GET_CONTACTS',
  UPDATE_CONTACTS: 'UPDATE_CONTACTS',
  SET_CONTACTS_EMAIL: 'SET_CONTACTS_EMAIL',
  TEST_ASYNC: 'TEST_ASYNC',
  SET_PORTAL_PACKAGE_JSON: 'SET_PORTAL_PACKAGE_JSON',
}
